// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Rocks.Models;

#nullable disable

namespace Rocks.Migrations
{
    [DbContext(typeof(RockContext))]
    [Migration("20231002183408_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Rocks.Models.Rock", b =>
                {
                    b.Property<int>("RockId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RockId"));

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Home")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Shape")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Size")
                        .HasColumnType("int");

                    b.Property<int>("Weight")
                        .HasColumnType("int");

                    b.HasKey("RockId");

                    b.ToTable("Rocks");

                    b.HasData(
                        new
                        {
                            RockId = 1,
                            Color = "Polynesian",
                            Home = "Hawaii",
                            Name = "Dwayne",
                            Shape = "Built/Muscular/Good",
                            Size = 77,
                            Weight = 300
                        },
                        new
                        {
                            RockId = 2,
                            Color = "White",
                            Home = "Death Mountain",
                            Name = "Marbled Rock Roast",
                            Shape = "Meat",
                            Size = 1,
                            Weight = 800
                        },
                        new
                        {
                            RockId = 3,
                            Color = "White",
                            Home = "Rio",
                            Name = "Christ the Redeemer",
                            Shape = "Christ",
                            Size = 1176,
                            Weight = 1400000
                        },
                        new
                        {
                            RockId = 4,
                            Color = "Brown",
                            Home = "Bikini Bottom",
                            Name = "Parick's House",
                            Shape = "Boulder",
                            Size = 12,
                            Weight = 3
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
